name: test_with_cli

on:
  workflow_dispatch:

jobs:
  test_with_cli:
    name: Test With CLI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: |
          pip install -r maro/requirements.build.txt
          pip install -r tests/requirements.test.txt

      - name: Compile cython files
        run: |
          cython ./maro/backends/backend.pyx ./maro/backends/np_backend.pyx ./maro/backends/raw_backend.pyx ./maro/backends/frame.pyx -3 -E FRAME_BACKEND=NUMPY,NODES_MEMORY_LAYOUT=ONE_BLOCK -X embedsignature=True

      - name: Install maro and deploy meta files
        run: |
          python setup.py install
          maro meta deploy

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo apt-key fingerprint 0EBFCD88
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose -s
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Setup ssh
        run: |
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y >/dev/null

      - name: Generate config
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: |
          python -m tests.cli.scripts.generate_config
          python -m unittest tests/cli/grass/test_grass.py
